version: '2.0'

services:
  tomcat:
    image: tomcat:8.0.53-jre8
    ports:
      - "8080:8080"
    volumes:
         - ./tomcat-users.xml:/usr/local/tomcat/conf/tomcat-users.xml
         - ./target/ROOT.war:/usr/local/tomcat/webapps/ROOT.war
         - ./target/ROOT:/usr/local/tomcat/webapps/ROOT
